In [2]:
import numpy as np

# Moving Averages 

### Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [10]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],dtype = "int32")
n = arr.shape[0]
k = 3

In [5]:
#total number of iterations will be
n - k + 1

11

In [12]:
def moving_average(x,k):
    
    n = x.shape[0]
    
    for i in range(n - k + 1):
        
        print(f' Y[{i}] = {np.mean(arr[i:i+k])}')
    
moving_average(arr,k)    

 Y[0] = 5.0
 Y[1] = 4.666666666666667
 Y[2] = 5.666666666666667
 Y[3] = 6.666666666666667
 Y[4] = 9.666666666666666
 Y[5] = 28.666666666666668
 Y[6] = 49.333333333333336
 Y[7] = 72.66666666666667
 Y[8] = 84.0
 Y[9] = 93.33333333333333
 Y[10] = 116.33333333333333


# Q2 Alexandre-Theophile Vandermonde.



In [7]:
#using numpy function to verify my input 
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [15]:
x ** (N-1),arr[:,0]

(array([ 1,  4,  9, 25], dtype=int32), array([1., 1., 1., 1.]))

In [16]:
# implementing my own papers 

M = len(x)

arr = np.ones((M,N))


for i in range(N-1):
    
    # x and the rows have the same shape,
    
    arr[:,i] = x ** (N - i - 1)
 
    



arr

(4, 3)


array([[ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [25.,  5.,  1.]])